/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

calculadora_response *
sumar_1_svc(float arg1, float arg2,  struct svc_req *rqstp)
{
	static calculadora_response  result;

	// libera la memoria que se asigno * (para el resultado) en una ejecución previa del servidor
	xdr_free((xdrproc_t) xdr_calculadora_response, (char*)&result);

	result.calculadora_response_u.result = arg1 + arg2;

	return &result;
}

calculadora_response *
restar_1_svc(float arg1, float arg2,  struct svc_req *rqstp)
{
	static calculadora_response result;

	xdr_free((xdrproc_t) xdr_calculadora_response, (char*) &result);


	result.calculadora_response_u.result= arg1 - arg2;


	return &result;
}

calculadora_response *
multiplicar_1_svc(float arg1, float arg2,  struct svc_req *rqstp)
{
	static calculadora_response  result;

	xdr_free((xdrproc_t) xdr_calculadora_response,(char*) &result);


	result.calculadora_response_u.result = arg1 * arg2;

	return &result;
}

calculadora_response *
dividir_1_svc(float arg1, float arg2,  struct svc_req *rqstp)
{
	static calculadora_response  result;
	if(arg2 == 0){
		result.err = 1;
	}

	xdr_free((xdrproc_t) xdr_calculadora_response,(char*) &result);

	result.calculadora_response_u.result = arg1 / arg2;

	return &result;
}
