/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct calculadora_response {
	int err;
	union {
		float result;
	} calculadora_response_u;
};
typedef struct calculadora_response calculadora_response;

struct sumar_1_argument {
	float arg1;
	float arg2;
};
typedef struct sumar_1_argument sumar_1_argument;

struct restar_1_argument {
	float arg1;
	float arg2;
};
typedef struct restar_1_argument restar_1_argument;

struct multiplicar_1_argument {
	float arg1;
	float arg2;
};
typedef struct multiplicar_1_argument multiplicar_1_argument;

struct dividir_1_argument {
	float arg1;
	float arg2;
};
typedef struct dividir_1_argument dividir_1_argument;

#define CALCULADORA 0x20000001
#define CALCV1 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMAR 1
extern  calculadora_response * sumar_1(float , float , CLIENT *);
extern  calculadora_response * sumar_1_svc(float , float , struct svc_req *);
#define RESTAR 2
extern  calculadora_response * restar_1(float , float , CLIENT *);
extern  calculadora_response * restar_1_svc(float , float , struct svc_req *);
#define MULTIPLICAR 3
extern  calculadora_response * multiplicar_1(float , float , CLIENT *);
extern  calculadora_response * multiplicar_1_svc(float , float , struct svc_req *);
#define DIVIDIR 4
extern  calculadora_response * dividir_1(float , float , CLIENT *);
extern  calculadora_response * dividir_1_svc(float , float , struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMAR 1
extern  calculadora_response * sumar_1();
extern  calculadora_response * sumar_1_svc();
#define RESTAR 2
extern  calculadora_response * restar_1();
extern  calculadora_response * restar_1_svc();
#define MULTIPLICAR 3
extern  calculadora_response * multiplicar_1();
extern  calculadora_response * multiplicar_1_svc();
#define DIVIDIR 4
extern  calculadora_response * dividir_1();
extern  calculadora_response * dividir_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_calculadora_response (XDR *, calculadora_response*);
extern  bool_t xdr_sumar_1_argument (XDR *, sumar_1_argument*);
extern  bool_t xdr_restar_1_argument (XDR *, restar_1_argument*);
extern  bool_t xdr_multiplicar_1_argument (XDR *, multiplicar_1_argument*);
extern  bool_t xdr_dividir_1_argument (XDR *, dividir_1_argument*);

#else /* K&R C */
extern bool_t xdr_calculadora_response ();
extern bool_t xdr_sumar_1_argument ();
extern bool_t xdr_restar_1_argument ();
extern bool_t xdr_multiplicar_1_argument ();
extern bool_t xdr_dividir_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
