/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora_matriz.h"


matriz_response *
suma_matrices_1_svc(matriz arg1, matriz arg2,  struct svc_req *rqstp)
{
	static matriz_response result;
	
	if(arg1.fil != arg2.fil || arg1.col != arg2.col){
		result.err = 1;
	}
	else{
	xdr_free((xdrproc_t) xdr_suma_matrices_1_argument, (char *) &result);

	result.matriz_response_u.result.fil = arg1.fil;
	result.matriz_response_u.result.col = arg2.col;
	result.matriz_response_u.result.mat.mat_len= result.matriz_response_u.result.fil*result.matriz_response_u.result.col;
	result.matriz_response_u.result.mat.mat_val = malloc(result.matriz_response_u.result.mat.mat_len*sizeof(float));

	
	for(int i=0;i<result.matriz_response_u.result.mat.mat_len;i++){
      	result.matriz_response_u.result.mat.mat_val[i] = arg1.mat.mat_val[i] + arg1.mat.mat_val[i]; 
  	}
	}

	return &result;
}

matriz_response *
resta_matrices_1_svc(matriz arg1, matriz arg2,  struct svc_req *rqstp)
{
	static matriz_response result;
	xdr_free((xdrproc_t) xdr_resta_matrices_1_argument, (char *) &result);

	if(arg1.fil != arg2.fil || arg1.col != arg2.col){
		result.err = 1;
	}
	else{

	result.matriz_response_u.result.fil = arg1.fil;
	result.matriz_response_u.result.col = arg2.col;
	result.matriz_response_u.result.mat.mat_len= result.matriz_response_u.result.fil*result.matriz_response_u.result.col;
	result.matriz_response_u.result.mat.mat_val = malloc(result.matriz_response_u.result.mat.mat_len*sizeof(float));

	
	for(int i=0;i<result.matriz_response_u.result.mat.mat_len;i++){
      	result.matriz_response_u.result.mat.mat_val[i] = arg1.mat.mat_val[i] - arg1.mat.mat_val[i]; 
  	}
	}

	return &result;
}



matriz_response *
mult_matrices_1_svc(matriz arg1, matriz arg2,  struct svc_req *rqstp)
{
	static matriz_response result;
	xdr_free((xdrproc_t) xdr_mult_matrices_1_argument, (char *) &result);

	if(arg1.col != arg2.fil){
		result.err = 1;
	}
	else{


	result.matriz_response_u.result.fil = arg1.fil;
	result.matriz_response_u.result.col = arg2.col;
	printf("fil: %u , col: %u\n",result.matriz_response_u.result.fil,result.matriz_response_u.result.col);
	result.matriz_response_u.result.mat.mat_len= result.matriz_response_u.result.fil*result.matriz_response_u.result.col;
	result.matriz_response_u.result.mat.mat_val = malloc(result.matriz_response_u.result.mat.mat_len*sizeof(float));

	for(int i=0;i<arg1.fil;i++){
      	for(int j=0;j<arg2.col;j++){
          	result.matriz_response_u.result.mat.mat_val[result.matriz_response_u.result.fil*i+j]=0;
			  
          	for(int k=0; k < arg1.col;k++){
				printf("1: %u , 2: %u",arg1.fil*i+k,arg2.col*k+j);  
				printf(" j: %u",j);
				printf(" k: %u\n",k);
            	result.matriz_response_u.result.mat.mat_val[result.matriz_response_u.result.fil*i+j] += (arg1.mat.mat_val[arg1.fil*i+k] * arg2.mat.mat_val[arg2.col*k+j]);
				
          	}
			  printf(" Termina suma: %f\n",result.matriz_response_u.result.mat.mat_val[result.matriz_response_u.result.fil*i+j]);
      	}
  	}

	for (int i = 0; i < result.matriz_response_u.result.fil; i++) {
        for (int j = 0; j < result.matriz_response_u.result.col; j++) {
            printf("%f ", result.matriz_response_u.result.mat.mat_val[result.matriz_response_u.result.fil*i+j]);
        }
        printf("\n");
    }
	}

	return &result;
}