/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculadora_matriz.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

matriz_response *
suma_matrices_1(matriz arg1, matriz arg2,  CLIENT *clnt)
{
	suma_matrices_1_argument arg;
	static matriz_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, SUMA_MATRICES, (xdrproc_t) xdr_suma_matrices_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_matriz_response, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

matriz_response *
resta_matrices_1(matriz arg1, matriz arg2,  CLIENT *clnt)
{
	resta_matrices_1_argument arg;
	static matriz_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, RESTA_MATRICES, (xdrproc_t) xdr_resta_matrices_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_matriz_response, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

matriz_response *
mult_matrices_1(matriz arg1, matriz arg2,  CLIENT *clnt)
{
	mult_matrices_1_argument arg;
	static matriz_response clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	if (clnt_call (clnt, MULT_MATRICES, (xdrproc_t) xdr_mult_matrices_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_matriz_response, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
